
[flywheel]

	[flywheel.bronze_flywheel]
		#Range: 0 ~ 8192
		bronzeFlywheelCapacity = 32
		#Range: 0 ~ 8192
		bronzeFlywheelSpeed = 32
		#Range: 0 ~ 8192
		bronzeFlywheelSteamConsumptionPerTick = 12
		#Range: 0 ~ 1048576
		bronzeFlywheelSteamStorage = 32000

	[flywheel.cast_iron_flywheel]
		#Range: 0 ~ 8192
		castIronFlywheelCapacity = 64
		#Range: 0 ~ 8192
		castIronFlywheelSpeed = 32
		#Range: 0 ~ 8192
		castIronFlywheelSteamConsumptionPerTick = 24
		#Range: 0 ~ 1048576
		castIronFlywheelSteamStorage = 64000

	[flywheel.steel_flywheel]
		#Range: 0 ~ 8192
		steelFlywheelCapacity = 96
		#Range: 0 ~ 8192
		steelFlywheelSpeed = 32
		#Range: 0 ~ 1048576
		steelFlywheelSteamConsumptionPerTick = 48
		#Range: 0 ~ 1048576
		steelFlywheelSteamStorage = 96000

[dynamo]
	#If dynamo is disabled in the server config, the following will be ignored!
	#Range: 0 ~ 8192
	dynamoFeMaxOut = 256
	#Range: 0 ~ 8192
	dynamoFeCapacity = 2048
	#Range: 0 ~ 8192
	dynamoImpact = 16
	#Range: 0.0 ~ 1.0
	dynamoEfficiency = 0.75

[cogwheel]
	#For those who want to make the game more challenging, you can add stress impact to cogwheels!
	#Range: 0.0 ~ 1.0
	bronzeCogwheelImpact = 0.0
	#Range: 0.0 ~ 1.0
	castIronCogwheelImpact = 0.0
	#Range: 0.0 ~ 1.0
	steelCogwheelImpact = 0.0

